# Generated by Django 3.1.2 on 2020-11-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_auto_20201103_1711'),
        ('check', '0003_customer_profile_pic'),
    ]

    operations = [
    ]
